/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/model-assets/uploads/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize presigned upload targets */
        post: operations["initUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-assets/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify uploaded files and transition to READY */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/model-assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get model asset status */
        get: operations["getModelAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a READY asset as a product */
        post: operations["publishProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published products */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product detail */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}/ar-asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AR asset for a product */
        get: operations["getProductArAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{id}/chat-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a chat room for a product */
        post: operations["createProductChatRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat-rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user's chat rooms */
        get: operations["listChatRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat-rooms/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get messages in a chat room */
        get: operations["getChatMessages"];
        put?: never;
        /** Send a message in a chat room */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available auth providers */
        get: operations["getAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OAuth callback handler */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user summary stats */
        get: operations["getUserSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            detail?: string;
        };
        UploadInitRequest: {
            /** @enum {string} */
            dims_source?: "ios_lidar" | "ios_manual" | "unknown";
            dims_width?: number | null;
            dims_height?: number | null;
            dims_depth?: number | null;
            /** Format: uuid */
            capture_session_id?: string | null;
            files: {
                /** @enum {string} */
                role: "MODEL_USDZ" | "MODEL_GLB" | "PREVIEW_PNG";
                size_bytes: number;
            }[];
        };
        UploadInitResponse: {
            /** Format: uuid */
            asset_id: string;
            /** @enum {string} */
            status: "UPLOADING";
            presigned_uploads: {
                role: string;
                /** Format: uri */
                url: string;
                /** Format: date-time */
                expires_at: string;
            }[];
        };
        UploadCompleteRequest: {
            /** Format: uuid */
            asset_id: string;
            files: {
                /** @enum {string} */
                role: "MODEL_USDZ" | "MODEL_GLB" | "PREVIEW_PNG";
                size_bytes: number;
                checksum_sha256: string;
            }[];
        };
        UploadCompleteResponse: {
            /** Format: uuid */
            asset_id: string;
            /** @enum {string} */
            status: "READY";
            files: {
                role: string;
                verified: boolean;
            }[];
        };
        ModelAssetResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_id: string;
            /** @enum {string} */
            status: "INITIATED" | "UPLOADING" | "READY" | "FAILED" | "PUBLISHED";
            /** @enum {string} */
            availability: "READY" | "PROCESSING" | "NONE";
            /** @enum {string|null} */
            dims_source?: "ios_lidar" | "ios_manual" | "unknown" | null;
            dims_width?: number | null;
            dims_height?: number | null;
            dims_depth?: number | null;
            files: components["schemas"]["AssetFileInfo"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AssetFileInfo: {
            role: string;
            storage_key: string;
            size_bytes: number;
            checksum_sha256: string;
        };
        ArAssetResponse: {
            /** @enum {string} */
            availability: "READY" | "PROCESSING" | "NONE";
            /** Format: uuid */
            asset_id?: string | null;
            files: {
                role: string;
                /** Format: uri */
                url: string;
                /** @enum {string} */
                type: "model" | "preview";
            }[];
            /** @enum {string|null} */
            dims_source?: "ios_lidar" | "ios_manual" | "unknown" | null;
            /** @enum {string|null} */
            dims_trust?: "high" | "medium" | "low" | null;
        };
        PublishRequest: {
            /** Format: uuid */
            asset_id: string;
            title: string;
            description?: string;
            price_cents: number;
        };
        ProductResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            asset_id: string;
            title: string;
            description?: string | null;
            price_cents: number;
            /** Format: uuid */
            seller_id: string;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ProductListResponse: {
            products: components["schemas"]["ProductResponse"][];
            total: number;
            page: number;
            limit: number;
        };
        CreateChatRoomRequest: {
            subject: string;
        };
        ChatRoomResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            /** Format: uuid */
            buyer_id: string;
            /** Format: uuid */
            seller_id: string;
            subject: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_message_at?: string | null;
        };
        ChatMessageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            room_id: string;
            /** Format: uuid */
            sender_id: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        SendMessageRequest: {
            body: string;
        };
        AuthProvidersResponse: {
            providers: string[];
        };
        AuthTokenResponse: {
            access_token: string;
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            name: string;
            provider: string;
            /** Format: date-time */
            created_at: string;
        };
        UserSummaryResponse: {
            user: components["schemas"]["UserResponse"];
            product_count: number;
            unread_messages: number;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInitRequest"];
            };
        };
        responses: {
            /** @description Presigned URLs issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInitResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCompleteRequest"];
            };
        };
        responses: {
            /** @description Upload verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCompleteResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getModelAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelAssetResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    publishProduct: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Product published */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listProducts: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProductArAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AR asset info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArAssetResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createProductChatRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatRoomRequest"];
            };
        };
        responses: {
            /** @description Chat room created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatRoomResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listChatRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat room list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        rooms: components["schemas"]["ChatRoomResponse"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getChatMessages: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: components["schemas"]["ChatMessageResponse"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message sent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProvidersResponse"];
                };
            };
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code: string;
                state?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Auth token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
